version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
    labels:
      - dependencies
    assignees:
      - danirod
    ignore:
      - dependency-name: "@types/node"
        versions:
          - ">= 17"
    commit-message:
      prefix: chore
      include: scope
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: monthly
    labels:
      - dependencies
    assignees:
      - danirod
    ignore:
      - dependency-name: node
        versions:
          - ">= 17"
    commit-message:
      prefix: chore
      include: scope
