title: "makibot"
description: "El bot de moderación y entretenimiento del servidor de Discord de makigas"
baseurl: "/makibot"
url: "https://makigas.github.io"

# Theme settings
remote_theme: pmarsceill/just-the-docs
search_enabled: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Editar esta página en GitHub"
gh_edit_repository: "https://github.com/makigas/makibot" # the github URL for your repo
gh_edit_branch: "trunk" # the branch that your docs is served from
gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately
